const menuList=[
    {
        "moduleNm":"系统管理",
        "moduleValid":"0",
        "pModuleId":"",
        "moduleHide":"0",
        "helpTitle":"",
        "moduleType":"0",
        "paramOpCode":"",
        "smallIcon":"systemmanagement.png",
        "helpPage":"",
        "moduleId":"2016030300000001",
        "child":[
            {
                "moduleNm":"数据字典",
                "moduleValid":"0",
                "pModuleId":"2016030300000001",
                "moduleHide":"0",
                "helpTitle":"数据字典",
                "moduleType":"1",
                "paramOpCode":"",
                "helpPage":"",
                "moduleOpCode":"common_dictionarys",
                "moduleId":"common_dictionarys",
                "child":[

                ]
            },
            {
                "helpTitle":"租户管理",
                "bigIcon":"",
                "moduleType":"1",
                "moduleTarget":"",
                "moduleOpCode":"tenants",
                "moduleNm":"租户管理",
                "moduleValid":"0",
                "pModuleId":"2016030300000001",
                "moduleHide":"0",
                "paramOpCode":"option",
                "smallIcon":"",
                "helpPage":"",
                "moduleId":"2017112000000001",
                "child":[

                ],
                "moduleUrl":""
            }],
        "moduleUrl":"dd"
    },
    {
        "moduleNm":"公共信息管理",
        "moduleValid":"0",
        "pModuleId":"",
        "moduleHide":"0",
        "helpTitle":"公共信息管理",
        "moduleType":"0",
        "paramOpCode":"",
        "smallIcon":"daping11.png",
        "helpPage":"",
        "moduleId":"common",
        "child":[]
    },
    {
        "moduleNm":"运维自动化",
        "moduleValid":"0",
        "pModuleId":"",
        "moduleHide":"0",
        "helpTitle":"",
        "moduleType":"0",
        "paramOpCode":"",
        "smallIcon":"deploy2.png",
        "helpPage":"",
        "moduleId":"oap20171218",
        "child":[],
        "moduleUrl":""
    },
    {
        "helpTitle":"大屏管理",
        "bigIcon":"",
        "moduleType":"0",
        "moduleTarget":"",
        "moduleOpCode":"",
        "moduleNm":"大屏管理",
        "moduleValid":"0",
        "pModuleId":"",
        "moduleHide":"",
        "paramOpCode":"",
        "smallIcon":"daping.png",
        "helpPage":"",
        "moduleId":"2017111600000002",
        "child":[],
        "moduleUrl":""
    },
    {
        "helpTitle":"报表管理",
        "bigIcon":"",
        "moduleType":"0",
        "moduleTarget":"",
        "moduleOpCode":"",
        "moduleNm":"报表管理",
        "moduleValid":"0",
        "pModuleId":"",
        "moduleHide":"0",
        "paramOpCode":"",
        "smallIcon":"system.png",
        "helpPage":"",
        "moduleId":"2017121100000000",
        "child":[],
        "moduleUrl":""
    }
];
export default menuList;